artifact_location: file:///C:/Users/ADMIN/Desktop/Object Detection - biển số xe/ObjectDetection-Nhan_dien_bien_so_xe/runs/mlflow/507095508978573526
creation_time: 1753349634901
experiment_id: '507095508978573526'
last_update_time: 1753349634901
lifecycle_stage: active
name: /Shared/Ultralytics
