artifact_location: file:///C:/Users/ADMIN/Desktop/Object Detection - biển số xe/ObjectDetection-Nhan_dien_bien_so_xe/runs/mlflow/0
creation_time: 1753349634890
experiment_id: '0'
last_update_time: 1753349634890
lifecycle_stage: active
name: Default
